apiVersion: v1
kind: Service
metadata:
  name: vespa
  labels:
    app: vespa
spec:
  selector:
    app: vespa
  type: NodePort
  ports:
    - name: container
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: config
      port: 19071
      targetPort: 19071
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa
  labels:
    app: vespa
spec:
  replicas: 1
  serviceName: vespa
  selector:
    matchLabels:
      app: vespa
  template:
    metadata:
      labels:
        app: vespa
    spec:
      containers:
        - name: vespa
          image: vespaengine/vespa
          imagePullPolicy: Always
          env:
            - name: VESPA_CONFIGSERVERS
              value: vespa-0.vespa.default.svc.cluster.local
          securityContext:
            runAsUser: 1000
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /state/v1/health
              port: 19071
              scheme: HTTP
