name: Check Ruff
on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
            python-version: 3.11
      - name: Install dependencies
        run: pip install ruff
      - name: Check ruff
        run: ruff check backend/app
